// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3HbBGGVFph0ReW2xCYNQQDSG96V4rL-0',
    appId: '1:510866738100:web:00686f25d69e39090840e1',
    messagingSenderId: '510866738100',
    projectId: 'buapnet',
    authDomain: 'buapnet.firebaseapp.com',
    storageBucket: 'buapnet.firebasestorage.app',
    measurementId: 'G-4T7DKJQPF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAsAAjWafBbfUqW01bXfJLAbF7sz7poZ8',
    appId: '1:510866738100:android:8f9c1b20d9055c9b0840e1',
    messagingSenderId: '510866738100',
    projectId: 'buapnet',
    storageBucket: 'buapnet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBR0m-hF63nlr1OvtmOx_0z025Xxc10y4',
    appId: '1:510866738100:ios:3f0e00bb9c842ab10840e1',
    messagingSenderId: '510866738100',
    projectId: 'buapnet',
    storageBucket: 'buapnet.firebasestorage.app',
    iosBundleId: 'com.example.buapnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBR0m-hF63nlr1OvtmOx_0z025Xxc10y4',
    appId: '1:510866738100:ios:3f0e00bb9c842ab10840e1',
    messagingSenderId: '510866738100',
    projectId: 'buapnet',
    storageBucket: 'buapnet.firebasestorage.app',
    iosBundleId: 'com.example.buapnet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3HbBGGVFph0ReW2xCYNQQDSG96V4rL-0',
    appId: '1:510866738100:web:239bbac2ac4c8de30840e1',
    messagingSenderId: '510866738100',
    projectId: 'buapnet',
    authDomain: 'buapnet.firebaseapp.com',
    storageBucket: 'buapnet.firebasestorage.app',
    measurementId: 'G-4KWKS2DCSY',
  );
}
