name: buapnet
description: Foro centralizado para la atención de estudiantes universitarios.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_messaging: ^14.6.5
  
  # UI
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  timeago: ^3.5.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  
  # Estado
  flutter_local_notifications: ^14.0.0
  provider: ^6.0.5
  
  # Utilidades
  flutter_image_compress: ^1.1.3
  intl: ^0.18.1
  image_picker: ^1.0.2
  image_cropper: ^5.0.0
  path_provider: ^2.1.0
  uuid: ^3.0.7
  logger: ^2.0.1
  http: ^1.1.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  connectivity_plus: ^4.0.2
  js: ^0.6.5
  
  # Validación
  form_field_validator: ^1.1.0
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700